navigation:
- text: Install
  dropdown:
  - text: Platforms
    url: /platforms.html
  - divider
  - text: Install Cucumber-JVM
    url: /install-cucumber-jvm.html
  - text: Install Cucumber-Ruby
    url: /install-cucumber-ruby.html
  - text: Install Cucumber-Rails
    url: /install-cucumber-rails.html
  - text: Install Cucumber-JavaScript
    url: /install-cucumber-js.html
- text: Running
  url: /running.html
- text: Gherkin
  url: /gherkin.html
- text: API
  dropdown:
  - text: API Overview
    url: /api-overview.html
  - text: Glue Code
    url: /glue-code.html
  - text: Step Definitions
    url: /step-definitions.html
  - text: Hooks
    url: /hooks.html
  - text: Reports
    url: /reports.html
  - divider: Cucumber-JVM
  - text: Dependency Injection
    url: /dependency-injection.html
- text: Learn more
  dropdown:
  - text: Browser Automation
    url: /browser-automation.html
  - text: Reports
    url: /reports.html
  - text: Databases
    url: /databases.html
- text: Ecosystem
  dropdown:
  - text: Community Help
    url: /community-help.html
  - text: Source code
    url: /source-code.html
  - text: Editors and IDEs
    url: /editors-and-ides.html


pygments: true
